// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFBm8hFUuEdJYOwB6bKyD3IBZ_WoU_Uk',
    appId: '1:756021854019:web:d7b215c80539237069f9f6',
    messagingSenderId: '756021854019',
    projectId: 'mentoons-70252',
    authDomain: 'mentoons-70252.firebaseapp.com',
    storageBucket: 'mentoons-70252.firebasestorage.app',
    measurementId: 'G-S8F9VH1ZK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlta5Bn6RbWYVbLfwZ9ITVUSuSXFFmt0',
    appId: '1:756021854019:android:53928f6abe648ae069f9f6',
    messagingSenderId: '756021854019',
    projectId: 'mentoons-70252',
    storageBucket: 'mentoons-70252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_LyROBk6oiu5Z1-zkvaDM5_f4BDo1yg',
    appId: '1:756021854019:ios:1c3a609aabb688fc69f9f6',
    messagingSenderId: '756021854019',
    projectId: 'mentoons-70252',
    storageBucket: 'mentoons-70252.firebasestorage.app',
    iosBundleId: 'com.example.mentoons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj_LyROBk6oiu5Z1-zkvaDM5_f4BDo1yg',
    appId: '1:756021854019:ios:1c3a609aabb688fc69f9f6',
    messagingSenderId: '756021854019',
    projectId: 'mentoons-70252',
    storageBucket: 'mentoons-70252.firebasestorage.app',
    iosBundleId: 'com.example.mentoons',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpFBm8hFUuEdJYOwB6bKyD3IBZ_WoU_Uk',
    appId: '1:756021854019:web:37b59cd5b1437c9e69f9f6',
    messagingSenderId: '756021854019',
    projectId: 'mentoons-70252',
    authDomain: 'mentoons-70252.firebaseapp.com',
    storageBucket: 'mentoons-70252.firebasestorage.app',
    measurementId: 'G-J2V5FWYCMN',
  );
}
